### ISSUE TITLE
atwork_commander crashes when using default launchfile

### ISSUE THREAD

**Issue by marcomasa** [robocup-at-work/atwork-commander#20]
```
process[rosout-1]: started with pid [16686]
started core service [/rosout]
process[atwork_commander/core-2]: started with pid [16703]
[ INFO] [1587860351.601491613]: [REFBOX] Try to read task definitions from '//atwork_commander/tasks'
process[atwork_commander/communication-3]: started with pid [16711]
[ INFO] [1587860351.602970098]: [REFBOX] Read 8 tasks from paramet er server
[ INFO] [1587860351.603020603]: [REFBOX] ry to read workstations from '//atwork_commander/arena/workstations'
[ INFO] [1587860351.603044501]: [REFBOX] ry to read waypoints from '//atwork_commander/arena/waypoints'
[ INFO] [1587860351.603061552]: [REFBOX] ry to read available objects from '//atwork_commander/arena/objects'
'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
The traceback for the exception was written to the log file
[ INFO] [1587860351.605855841]: [REFBOX] Read 12 workstations from parameter server
[ INFO] [1587860351.606006741]: [REFBOX] try to read PP cavities from '//atwork_commander/arena/cavities'
[ INFO] [1587860351.606950733]: [REFBOX] read 11 PP cavities from parameter server
[ INFO] [1587860351.624770940]: [REFBOX] initialized
[ INFO] [1587860351.632903241]: [REFBOX-COM] Try to load the following com plugins: [ atwork_commander::com_plugin::ros::TaskArenaCentric atwork_commander::com_plugin::ros::TaskObjectCentric]
[atwork_commander/communication-3] killing on exit
[atwork_commander/core-2] killing on exit
[ INFO] [1587860351.682269406]: [main|com] successfully initialized plugin "atwork_commander::com_plugin::ros::TaskArenaCentric"
communication: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
```

**Comment by marcomasa** [comment]
Verbose Output is even shorter ?

```
started core service [/rosout]
process[atwork_commander/core-2]: started with pid [17150]
process[atwork_commander/communication-3]: started with pid [17163]
'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
The traceback for the exception was written to the log file
[ INFO] [1587860442.826745779]: [REFBOX-COM] Try to load the following com plugins: [ atwork_commander::com_plugin::ros::TaskArenaCentric atwork_commander::com_plugin::ros::TaskObjectCentric]
[atwork_commander/communication-3] killing on exit
[atwork_commander/core-2] killing on exit
[ INFO] [1587860442.847782180]: [REFBOX] Try to read task definitions from '//atwork_commander/tasks'
[ INFO] [1587860442.881234117]: [main|com] successfully initialized plugin "atwork_commander::com_plugin::ros::TaskArenaCentric"
communication: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
11[rosout-1] killing on exit
[master] killing on exit
```

**Comment by marcomasa** [comment]
If you disable multimaster, this problem does not occur.
It is enabled by default.

**Comment by steup** [comment]
Can you post the logfile please. That enables  me to see where the python parsing error comes from.

**Comment by steup** [comment]
Tested through integration test on Xenial Kinetic and Bionix Melodic. Both work.

**Comment by marcomasa** [comment]
```
[rosmaster.main][INFO] 2020-04-29 17:12:37,036: initialization complete, waiting for shutdown
[rosmaster.main][INFO] 2020-04-29 17:12:37,036: Starting ROS Master Node
[xmlrpc][INFO] 2020-04-29 17:12:37,037: XML-RPC server binding to 127.0.0.1:11311
[xmlrpc][INFO] 2020-04-29 17:12:37,037: Started XML-RPC server [http://localhost:11311/]
[xmlrpc][INFO] 2020-04-29 17:12:37,037: xml rpc node: starting XML-RPC server
[rosmaster.master][INFO] 2020-04-29 17:12:37,037: Master initialized: port[11311], uri[http://localhost:11311/]
[rosmaster.master][INFO] 2020-04-29 17:12:37,087: +PARAM [/run_id] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:12:37,089: +PARAM [/roslaunch/uris/host_localhost__33447] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:12:37,332: +PARAM [/rosversion] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:12:37,333: +PARAM [/rosdistro] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:12:37,342: +SERVICE [/rosout/get_loggers] /rosout http://localhost:34223/
[rosmaster.master][INFO] 2020-04-29 17:12:37,343: +SERVICE [/rosout/set_logger_level] /rosout http://localhost:34223/
[rosmaster.master][INFO] 2020-04-29 17:12:37,344: +PUB [/rosout_agg] /rosout http://localhost:34223/
[rosmaster.master][INFO] 2020-04-29 17:12:37,346: +SUB [/rosout] /rosout http://localhost:34223/
[rosmaster.master][INFO] 2020-04-29 17:15:26,539: +PARAM [/roslaunch/uris/host_localhost__36317] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,546: +PARAM [/atwork_commander/tasks/BTT2/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/FINAL/container_placing] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/RTT/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/BTT1/arbitrary_surfaces] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/FINAL/ref_cavity_orientation] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/BMT/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/arena/workstations/WS05] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/arena/workstations/WS04] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/FINAL/object_types/CONTAINER_RED] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/arena/workstations/WS06] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/arena/workstations/WS01] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/RTT/tt_grasping] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/FINAL/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/arena/workstations/WS08] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/multimaster_sync/ignore_services] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/PPT/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/FINAL/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,547: +PARAM [/atwork_commander/tasks/BTT3/arbitrary_surfaces] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/arena/workstations/PP01] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/arena/objects/CONTAINER_RED] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/BTT1/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/arena/cavities] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/FINAL/ref_orientation] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/BMT/ref_position] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/BTT2/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/BTT1/decoys] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/arena/workstations/TT01] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/FINAL/shelfes_placing] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/FINAL/object_types/CONTAINER_BLUE] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/BTT2/arbitrary_surfaces] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/BTT3/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/PPT/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/FINAL/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/tasks/FINAL/ref_tt_direction] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,548: +PARAM [/atwork_commander/arena/objects/M20_100] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BTT3/obstacles] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/arena/workstations/SH02] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BTT2/decoys] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/arena/workstations/SH01] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/arena/objects/MOTOR] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/rosdistro] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BTT1/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BTT3/shelfes_placing] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/arena/workstations/WS07] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BTT3/shelfes_grasping] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BMT/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/BTT2/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/arena/workstations/WS03] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/FINAL/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/PPT/ref_cavity_position] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/arena/objects/AXIS] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,549: +PARAM [/atwork_commander/tasks/RTT/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BNT/obstacles] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BTT1/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/arena/objects/M30] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BTT3/decoys] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/core/debug] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/FINAL/tt_placing] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/FINAL/ref_cavity_rotation] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BTT1/ref_rotation] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BMT/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BNT/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BTT3/barrier_tapes] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/multimaster_sync/sync_topics] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/BTT3/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/arena/objects/R20] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/arena/objects/BEARING] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/arena/objects/CONTAINER_BLUE] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,550: +PARAM [/atwork_commander/tasks/FINAL/tt_grasping] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/PPT/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/PPT/ref_cavity_rotation] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/FINAL/arbitrary_surfaces] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/FINAL/barrier_tapes] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/FINAL/ref_position] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/BTT1/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/BTT2/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/RTT/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/arena/objects/M20] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/arena/objects/S40_40_G] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/FINAL/shelfes_grasping] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/arena/objects/S40_40_B] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/BTT3/object_types/CONTAINER_RED] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/BNT/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,551: +PARAM [/atwork_commander/tasks/BTT1/ref_position] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/arena/objects/DISTANCE_TUBE] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/PPT/pp_placing] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/arena/objects/F20_20_B] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/arena/objects/F20_20_G] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/FINAL/ref_rotation] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/FINAL/obstacles] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/BMT/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/PPT/normal_table_types] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/PPT/objects] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/BTT3/exec_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/BNT/waypoints] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/BTT2/obstacles] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/core/publish_frequency] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/arena/workstations/WS02] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/BMT/normal_table_types] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/FINAL/pp_placing] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/BNT/barrier_tapes] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,552: +PARAM [/atwork_commander/tasks/FINAL/decoys] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/BTT3/object_types/CONTAINER_BLUE] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/RTT/decoys] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/communication/plugins] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/BTT1/normal_table_types] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/core/robot_timeout] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/rosversion] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/FINAL/ref_cavity_position] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/RTT/tables] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/RTT/deliver_to_robot] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/arena/objects/BEARING_BOX] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/BTT3/prep_time] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,553: +PARAM [/atwork_commander/tasks/BTT1/barrier_tapes] by /roslaunch
[rosmaster.master][INFO] 2020-04-29 17:15:26,817: +PUB [/rosout] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,818: +SERVICE [/atwork_commander/core/get_loggers] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,819: +SERVICE [/atwork_commander/core/set_logger_level] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,827: publisherUpdate[/rosout] -> http://localhost:34223/ ['http://localhost:36675/']
[rosmaster.master][INFO] 2020-04-29 17:15:26,829: publisherUpdate[/rosout] -> http://localhost:34223/ ['http://localhost:36675/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2020-04-29 17:15:26,837: +SUB [/atwork_commander/internal/robot_state] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,838: +PUB [/atwork_commander/internal/task] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,839: +PUB [/atwork_commander/internal/state] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,840: +SERVICE [/atwork_commander/internal/start_task] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,841: +SERVICE [/atwork_commander/internal/generate_task] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,842: +SERVICE [/atwork_commander/internal/load_task] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,844: +SERVICE [/atwork_commander/internal/state_update] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:26,847: +PUB [/rosout] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,847: +SERVICE [/atwork_commander/communication/get_loggers] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,848: +SERVICE [/atwork_commander/communication/set_logger_level] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,854: +SUB [/atwork_commander/internal/task] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,854: +PUB [/atwork_commander/internal/robot_state] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,903: +SUB [/atwork_commander/robot_state] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,903: +PUB [/atwork_commander/task] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,905: +PUB [/atwork_commander/object_task] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:26,906: publisherUpdate[/rosout] -> http://localhost:34223/ ['http://localhost:36675/', 'http://localhost:45479/']
[rosmaster.master][INFO] 2020-04-29 17:15:26,907: publisherUpdate[/rosout] -> http://localhost:34223/ ['http://localhost:36675/', 'http://localhost:45479/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2020-04-29 17:15:26,907: publisherUpdate[/atwork_commander/internal/robot_state] -> http://localhost:36675/ ['http://localhost:45479/']
[rosmaster.master][INFO] 2020-04-29 17:15:26,907: publisherUpdate[/atwork_commander/internal/robot_state] -> http://localhost:36675/ ['http://localhost:45479/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2020-04-29 17:15:27,110: -PUB [/rosout] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:27,111: -PUB [/rosout] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:27,112: -PUB [/atwork_commander/internal/task] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:27,112: -PUB [/atwork_commander/internal/robot_state] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:27,113: -PUB [/atwork_commander/internal/state] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:27,113: -PUB [/atwork_commander/task] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:27,114: -SUB [/atwork_commander/internal/robot_state] /atwork_commander/core http://localhost:36675/
[rosmaster.master][INFO] 2020-04-29 17:15:27,115: -PUB [/atwork_commander/object_task] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:27,118: -SERVICE [/atwork_commander/core/get_loggers] /atwork_commander/core rosrpc://localhost:45207
[rosmaster.master][INFO] 2020-04-29 17:15:27,119: -SUB [/atwork_commander/internal/task] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:27,119: -SERVICE [/atwork_commander/core/set_logger_level] /atwork_commander/core rosrpc://localhost:45207
[rosmaster.master][INFO] 2020-04-29 17:15:27,120: -SUB [/atwork_commander/robot_state] /atwork_commander/communication http://localhost:45479/
[rosmaster.master][INFO] 2020-04-29 17:15:27,121: -SERVICE [/atwork_commander/internal/start_task] /atwork_commander/core rosrpc://localhost:45207
[rosmaster.master][INFO] 2020-04-29 17:15:27,121: -SERVICE [/atwork_commander/communication/get_loggers] /atwork_commander/communication rosrpc://localhost:38373
[rosmaster.master][INFO] 2020-04-29 17:15:27,122: -SERVICE [/atwork_commander/internal/generate_task] /atwork_commander/core rosrpc://localhost:45207
[rosmaster.master][INFO] 2020-04-29 17:15:27,122: -SERVICE [/atwork_commander/communication/set_logger_level] /atwork_commander/communication rosrpc://localhost:38373
[rosmaster.master][INFO] 2020-04-29 17:15:27,123: -SERVICE [/atwork_commander/internal/load_task] /atwork_commander/core rosrpc://localhost:45207
[rosmaster.master][INFO] 2020-04-29 17:15:27,124: -SERVICE [/atwork_commander/internal/state_update] /atwork_commander/core rosrpc://localhost:45207
[rosmaster.master][INFO] 2020-04-29 17:15:27,128: publisherUpdate[/rosout] -> http://localhost:34223/ ['http://localhost:45479/']
[rosmaster.master][INFO] 2020-04-29 17:15:27,128: publisherUpdate[/rosout] -> http://localhost:34223/ ['http://localhost:45479/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2020-04-29 17:15:27,128: publisherUpdate[/rosout] -> http://localhost:34223/ []
[rosmaster.master][INFO] 2020-04-29 17:15:27,129: publisherUpdate[/rosout] -> http://localhost:34223/ []: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2020-04-29 17:15:27,129: publisherUpdate[/atwork_commander/internal/task] -> http://localhost:45479/ []
[rosmaster.master][INFO] 2020-04-29 17:15:27,129: publisherUpdate[/atwork_commander/internal/task] -> http://localhost:45479/ []: sec=0.00, exception=<Fault -1: 'publisherUpdate: unknown method name'>
[rosmaster.master][INFO] 2020-04-29 17:15:27,130: publisherUpdate[/atwork_commander/internal/robot_state] -> http://localhost:36675/ []
[rosmaster.master][INFO] 2020-04-29 17:15:27,130: publisherUpdate[/atwork_commander/internal/robot_state] -> http://localhost:36675/ []: sec=0.00, exception=<Fault -1: 'publisherUpdate: unknown method name'>
[rosmaster.threadpool][ERROR] 2020-04-29 17:15:27,133: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault -1: 'publisherUpdate: unknown method name'>

[rosmaster.threadpool][ERROR] 2020-04-29 17:15:27,133: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault -1: 'publisherUpdate: unknown method name'>
```

**Comment by steup** [comment]
Couldn't reproduce maybe a local issue on your machine?

**Comment by marcomasa** [comment]
Now when i leave multimaster enabled, it says

Value error: 'ascii' codec can't decode byte 0xc3 in position 75: ordinal not in range(128)
The traceback for the exception was written to the log file


However, i think this is related to an issue occuring when a ROS package is not installed but called from a launchfile (python). I faced this issue earlier. Maybe update the dependencies (multimaster?).

**Comment by steup** [comment]
Is this still an issue or is it fixed through system changes?
